export const TOPICS = ['AUTH_TOPIC']
export const TRIP_TOPIC = 'TRIP_TOPIC'
export const USER_CREATED = 'USER_CREATED'
export const USER_UPDATED = 'USER_UPDATED'
export const TRIP_CREATED = 'TRIP_CREATED'
export const TRIP_UPDATED = 'TRIP_UPDATED'
export const PAYMENT_MODE_UPDATED = 'PAYMENT_MODE_UPDATED'
export const PAYMENT_CANCELLED = 'PAYMENT_CANCELLED'