apiVersion: apps/v1
kind: Deployment 
metadata:
  name: drive-chat-deployment
spec:
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - name: chat
          image: ashinjoy/chat-srv
          env:
           - name: PORT
             valueFrom:
              secretKeyRef:
                name: chat-secret
                key: PORT
           - name: MONGO_STRING
             valueFrom: 
              secretKeyRef:
                name: chat-secret
                key: MONGO_STRING
           - name: JWT_ACCESSTOKEN_SECRET
             valueFrom: 
               secretKeyRef:
                 name: chat-secret
                 key: JWT_ACCESSTOKEN_SECRET
           - name: JWT_REFRESHTOKEN_SECRET
             valueFrom: 
               secretKeyRef:
                 name: chat-secret
                 key: JWT_REFRESHTOKEN_SECRET  
           - name: MAIL
             valueFrom:
               secretKeyRef:
                 name: chat-secret
                 key: MAIL
           - name: PASSWORD
             valueFrom: 
               secretKeyRef:
                 name: chat-secret
                 key: PASSWORD
           - name: SESSION_SECRET
             valueFrom: 
               secretKeyRef:
                 name: chat-secret
                 key: SESSION_SECRET
           - name: BUCKET_NAME
             valueFrom: 
               secretKeyRef:
                 name: chat-secret
                 key: BUCKET_NAME  
           - name: REGION
             valueFrom: 
               secretKeyRef:
                 name: chat-secret
                 key: REGION
           - name: S3_ACCESSKEY
             valueFrom: 
               secretKeyRef:
                 name: chat-secret
                 key: S3_ACCESSKEY          
           - name: S3_SECRETKEY
             valueFrom: 
               secretKeyRef:
                 name: chat-secret
                 key: S3_SECRETKEY      
           - name: MAPBOX_ACCESS_TOKEN
             valueFrom: 
               secretKeyRef:
                 name: chat-secret
                 key: MAPBOX_ACCESS_TOKEN                                             
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service    
metadata:
  name: chat-service
spec:
  selector:
    app: chat
  ports:
  - name: auth
    port: 3004
    targetPort: 3004    