apiVersion: apps/v1
kind: Deployment 
metadata:
  name: drive-payment-deployment
spec:
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: ashinjoy/payment-srv
          env:
           - name: PORT
             valueFrom:
              secretKeyRef:
                name: payment-secret
                key: PORT
           - name: MONGO_STRING
             valueFrom: 
              secretKeyRef:
                name: payment-secret
                key: MONGO_STRING
           - name: JWT_ACCESSTOKEN_SECRET
             valueFrom: 
               secretKeyRef:
                 name: payment-secret
                 key: JWT_ACCESSTOKEN_SECRET
           - name: JWT_REFRESHTOKEN_SECRET
             valueFrom: 
               secretKeyRef:
                 name: payment-secret
                 key: JWT_REFRESHTOKEN_SECRET  
           - name: MAIL
             valueFrom: 
               secretKeyRef:
                 name: payment-secret
                 key: MAIL
           - name: PASSWORD
             valueFrom: 
               secretKeyRef:
                 name: payment-secret
                 key: PASSWORD
                 
           - name: SESSION_SECRET
             valueFrom: 
               secretKeyRef:
                 name: payment-secret
                 key: SESSION_SECRET
           - name: BUCKET_NAME
             valueFrom: 
               secretKeyRef:
                 name: payment-secret
                 key: BUCKET_NAME      
           - name: REGION
             valueFrom: 
               secretKeyRef:
                 name: payment-secret
                 key: REGION
           - name: S3_ACCESSKEY
             valueFrom: 
               secretKeyRef:
                 name: payment-secret
                 key: S3_ACCESSKEY 
           - name: S3_SECRETKEY
             valueFrom: 
               secretKeyRef:
                 name: payment-secret
                 key: S3_SECRETKEY 
           - name: STRIPE_SECRET_KEY
             valueFrom: 
               secretKeyRef:
                 name: payment-secret
                 key: STRIPE_SECRET_KEY
           - name: STRIPE_PUBLISHABLE_KEY
             valueFrom: 
               secretKeyRef:
                 name: payment-secret
                 key: STRIPE_PUBLISHABLE_KEY                                                                                          
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service    
metadata:
  name: payment-service
spec:
  selector:
    app: payment
  ports:
  - name: payment
    port: 3005
    targetPort: 3005    