apiVersion: apps/v1
kind: Deployment 
metadata:
  name: drive-trip-deployment
spec:
  selector:
    matchLabels:
      app: trip
  template:
    metadata:
      labels:
        app: trip
    spec:
      containers:
        - name: trip
          image: ashinjoy/trip-srv
          env:
           - name: PORT
             valueFrom:
              secretKeyRef:
                name: trip-secret
                key: PORT
           - name: MONGO_STRING
             valueFrom: 
              secretKeyRef:
                name: trip-secret
                key: MONGO_STRING
           - name: JWT_ACCESSTOKEN_SECRET
             valueFrom: 
               secretKeyRef:
                 name: trip-secret
                 key: JWT_ACCESSTOKEN_SECRET
           - name: JWT_REFRESHTOKEN_SECRET
             valueFrom: 
               secretKeyRef:
                 name: trip-secret
                 key: JWT_REFRESHTOKEN_SECRET  
           - name: PASSWORD
             valueFrom: 
               secretKeyRef:
                 name: trip-secret
                 key: PASSWORD
           - name: BUCKET_NAME
             valueFrom: 
               secretKeyRef:
                 name: trip-secret
                 key: BUCKET_NAME     
           - name: MAIL
             valueFrom: 
               secretKeyRef:
                 name: trip-secret
                 key: MAIL      
           - name: SESSION_SECRET
             valueFrom: 
               secretKeyRef:
                 name: trip-secret
                 key: SESSION_SECRET
           - name: REGION
             valueFrom: 
               secretKeyRef:
                 name: trip-secret
                 key: REGION      
           - name: TWILIO_ACCOUNT_SID
             valueFrom: 
               secretKeyRef:
                 name: trip-secret
                 key: TWILIO_ACCOUNT_SID
           - name: TWILIO_AUTH_TOKEN
             valueFrom: 
               secretKeyRef:
                 name: trip-secret
                 key: TWILIO_ACCOUNT_AUTH_TOKEN
           - name: TWILIO_ACCOUNT_PHONE
             valueFrom: 
               secretKeyRef:
                 name: trip-secret
                 key: TWILIO_ACCOUNT_PHONE
           - name: MAPBOX_ACCESS_TOKEN
             valueFrom: 
               secretKeyRef:
                 name: trip-secret
                 key: MAPBOX_ACCESS_TOKEN
           - name: S3_SECRETKEY
             valueFrom: 
               secretKeyRef:
                 name: trip-secret
                 key: S3_SECRETKEY
           - name: S3_ACCESSKEY
             valueFrom: 
               secretKeyRef:
                 name: trip-secret
                 key: S3_ACCESSKEY                                                                         
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service    
metadata:
  name: trip-service
spec:
  selector:
    app: trip
  ports:
  - name: trip
    port: 3003
    targetPort: 3003    